# Generated by Django 5.2.6 on 2025-10-03 18:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('periodicidade', models.IntegerField()),
                ('manual', models.FileField(blank=True, null=True, upload_to='manuais/')),
                ('endereco', models.CharField(max_length=255)),
                ('localizacao', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
