# Generated by Django 5.2.6 on 2025-10-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='mtbf',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='ativo',
            name='mttr',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
    ]
