# Generated by Django 5.2.6 on 2025-10-09 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ativo_mtbf_ativo_mttr'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('corretiva', 'Corretiva'), ('preditiva', 'Preditiva'), ('preventiva', 'Preventiva')], max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('finalizada', 'Finalizada')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_prevista', models.DateTimeField()),
                ('ativo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='api.ativo')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
