# Generated by Django 5.2.6 on 2025-10-19 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ordemservico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('ordem_servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.ordemservico')),
                ('data_inicio_execucao', models.DateTimeField()),
                ('data_fim_execucao', models.DateTimeField()),
                ('tempo_gasto', models.DurationField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('usuario_executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
