# Generated by Django 5.2.6 on 2025-10-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_manutencao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='mtbf',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='mttr',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
