# Generated by Django 5.2.6 on 2025-11-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_ativo_mtbf_alter_ativo_mttr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='mtbf',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='mttr',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
